export const ORIGINAL_TILE_SIZE = 16;
export const ORIGINAL_ZOOM = 1.35;
export const ORIGINAL_MAP_WIDTH_TILES = 100;
export const COLLISION_MAP_TILES = 100;
export const ORIGINAL_MAP_WIDTH_PX = ORIGINAL_MAP_WIDTH_TILES * ORIGINAL_TILE_SIZE * ORIGINAL_ZOOM; // 2160px